#version: { project-version }
backend:
  domain: example.hexcap.io # The domain name of the server (e.g. "example.hexcap.io")
  security:
    api-key: a1b2c3 # The API key for the backend
    api-secret: a1b2c3 # The secret key for the backend
